CODIGO_1:
	@python3 ./Asem/asem.py ./codigos/codigo_1.ccc
	@python3 ./gci/gci.py ./codigos/codigo_1.ccc

CODIGO_2:
	@python3 ./Asem/asem.py ./codigos/codigo_2.ccc
	@python3 ./gci/gci.py ./codigos/codigo_2.ccc

CODIGO_3:
	@python3 ./Asem/asem.py ./codigos/codigo_3.ccc
	@python3 ./gci/gci.py ./codigos/codigo_3.ccc
